Feature: Complete participant information for B2B2C users
	In order to complete the entire participant information
	As a partipant user
	I want to upload all the required files and fill out the profile information on particpant page

@completeParticipantInformation
Scenario Outline: Complete participant information for B2B2C users
	Given The user have entered into onboarding option
	| name   | lastName   | tile   | internalOption  | input   | emailPattern  |
	| <name> | <lastName> | <tile> | <internalOption>| <input> | <emailPattern>|
	When He fills out the fields related to tax situation
	| tile   | internalOption   | input   | isValidationSpigotGroup  | isValidationTileByParts  |
	| <tile> | <internalOption> | <input> | <isValidationSpigotGroup>| <isValidationTileByParts>|
	And He fills out the fields in user creation page so to complete participant information with the name <name> the lastname <lastName> the expectedquote <expectedQuote> and depends of user <isB2B2CUser> with the following consents
	| consentAditionalQuestion  | consentMarried  | consentFinantialReport  | consentReportableTransaction  | isMarriedOnBoarding  |
	| <consentAditionalQuestion>| <consentMarried>| <consentFinantialReport>| <consentReportableTransaction>| <isMarriedOnBoarding>|
	And He confirms the e-mail sent with the email, the name <name> and the lastname <lastName> for the type of user <isB2B2CUser>
	And The user have entered into participant page
	Then He enters into upload documents option to upload all required files <isRandomUploadFile>
	And Is validated and fill out all the information on the profile section
	| typeDependent  | firstNameDependent  | lastNameDependent  | dateOfBirth      | ssn        | dependentNotSsn | isMarriedOnBoarding  | spouseNotSsn  | isMarriedDependent  | markCompleteOptions  | maritalStatus  | hadDistributions  | directAndsameBankAccount  | checkMailedAndDirect  | isRandomUploadFile  | isB2B2CUser  | 
	| son            | Jhon                | Kent				| December,7,1962  | 123456789  | Yes             | <isMarriedOnBoarding>| <spouseNotSsn>| <isMarriedDependent>| <markCompleteOptions>| <maritalStatus>| <hadDistributions>| <directAndsameBankAccount>| <checkMailedAndDirect>| <isRandomUploadFile>| <isB2B2CUser>|
	| daughter       | Joseph              | Claus				| May,7,1972       | 515487987  | Yes             |						 |               |                     |                      |                |                   |                           |                       |                     |              |
	| parent         | Irina               | Maden				| June,7,1981      | 154678942  | No              |						 |               |                     |                      |                |                   |                           |                       |                     |              |
	| other          | Jhon                | Clark				| January,7,1969   | 193564874  | No              |						 |               |                     |                      |                |                   |                           |                       |                     |              |

	Examples: 
	|isB2B2CUser    | name       | lastName   | tile     | internalOption| input | expectedQuote  | complexityExpected | consentAditionalQuestion | consentMarried | consentFinantialReport | consentReportableTransaction   | isValidationSpigotGroup     | emailPattern                    | isValidationTileByParts  | isMarriedOnBoarding | spouseNotSsn | isMarriedDependent | markCompleteOptions | maritalStatus | hadDistributions                | directAndsameBankAccount | checkMailedAndDirect | isRandomUploadFile |			
	|Yes            | Christopher| Jackson    | 1        | No			 | 1     | 299            | Silver             | Yes                      | Yes            | Yes                    | Yes                            | No                          | lf.martinez+sub_cc_@globant.com | No                       | No                  | No           | No                 | Yes                 | Divorced      | Yes                             | Yes                      | No                   | No                 |
	|Yes            | Jhon       | Phillips   | 1        | No			 | 1     | 299            | Silver             | Yes                      | Yes            | Yes                    | Yes                            | No                          | lf.martinez+sub_cc_@globant.com | No                       | Yes                 | No           | No                 | Yes                 | Widowed       | I_did_not_have_any_distributions| No                       | No                   | No                 |
	|Yes            | Mark       | Jhonson    | 1        | No			 | 1     | 299            | Silver             | Yes                      | Yes            | Yes                    | Yes                            | No                          | lf.martinez+sub_cc_@globant.com | No                       | Yes                 | No           | No                 | No                  | Divorced      | No                              | No                       | No                   | No				 |
	|Yes            | Christopher| Morris     | 1        | No			 | 1     | 299            | Silver             | Yes                      | Yes            | Yes                    | Yes                            | No                          | lf.martinez+sub_cc_@globant.com | No                       | Yes                 | No           | No                 | No                  | Divorced      | No                              | No                       | Yes                  | No                 |	
	|Yes            | Ethan      | Mills      | 1        | No			 | 1     | 299            | Silver             | Yes                      | Yes            | Yes                    | Yes                            | No                          | lf.martinez+sub_cc_@globant.com | No                       | Yes                 | No           | No                 | No                  | Married       | Yes                             | No                       | No                   | No                 |
	|Yes            | Robert     | Pattson    | 1        | No			 | 1     | 299            | Silver             | Yes                      | Yes            | Yes                    | Yes                            | No                          | lf.martinez+sub_cc_@globant.com | No                       | Yes                 | No           | No                 | No                  | No_change     | No                              | No                       | No                   | No                 |
	|Yes            | Richard    | Williams   | 1        | No			 | 1     | 299            | Silver             | Yes                      | Yes            | Yes                    | Yes                            | No                          | lf.martinez+sub_cc_@globant.com | No                       | No                  | No           | Yes                | Yes                 | Married       | Yes                             | No                       | No                   | No                 |
	|Yes            | Edward     | Pierce     | 1        | No			 | 1     | 299            | Silver             | Yes                      | Yes            | Yes                    | Yes                            | No                          | lf.martinez+sub_cc_@globant.com | No                       | Yes				  | No           | Yes                | No                  | No_change     | No                              | No                       | No                   | Yes                |
	|Yes            | Thomas     | Mottola    | 9        | none			 | 1     | 199            | Gold               | Yes                      | Yes            | Yes                    | Yes                            | No                          | lf.martinez+sub_cc_@globant.com | No                       | No                  | No           | Yes                | No                  | No_change     | No                              | No                       | No                   | No                 |			
	|Yes            | Janet      | Damita     | 1,2,3    | No			 | 1     | 619            | Gold               | Yes                      | Yes            | Yes                    | Yes                            | No                          | lf.martinez+sub_cc_@globant.com | Yes                      | No                  | No           | Yes                | No                  | No_change     | No                              | No                       | No                   | No                 |
	|Yes            | John       | Martin     | 4,5,6    | No			 | 1     | 2314           | Platinum           | Yes                      | Yes            | Yes                    | Yes                            | No                          | lf.martinez+sub_cc_@globant.com | Yes                      | No                  | No           | Yes                | No                  | No_change     | No                              | No                       | No                   | No                 |
	|Yes            | Mariah     | Carey      | 7,8,9    | No			 | 1     | 359            | Gold               | Yes                      | Yes            | Yes                    | Yes                            | No                          | lf.martinez+sub_cc_@globant.com | Yes                      | No                  | No           | Yes                | No                  | No_change     | No                              | No                       | No                   | No                 |	
	|Yes            | Thomas     | Mottola    | 10,11    | No			 | 1     | 2449           | Gold               | Yes                      | Yes            | Yes                    | Yes                            | No                          | lf.martinez+sub_cc_@globant.com | Yes                      | No                  | No           | Yes                | No                  | No_change     | No                              | No                       | No                   | No                 |