Feature: Complete participant information for massive users previously created
	In order to complete the entire participant information
	As a partipant user
	I want to upload all the required files and fill out the profile information on particpant page

@completeParticipantInformationForMassiveUsers
Scenario Outline: Complete participant information with users previously created for B2B2C users
	Given The user have entered into participant page with a created user <email> <password>
	When He enters into upload documents option with an user created to upload all required files <isRandomUploadFile>	
	Then Is validated and fill out all the information on the profile section
	| typeDependent  | firstNameDependent  | lastNameDependent  | dateOfBirth      | ssn        | dependentNotSsn | isMarriedOnBoarding  | spouseNotSsn  | isMarriedDependent  | markCompleteOptions  | maritalStatus  | hadDistributions  | directAndsameBankAccount  | checkMailedAndDirect  | isRandomUploadFile  | isB2B2CUser | isCreatedUser |
	| son            | Jhon                | Kent				| December,7,1962  | 123456789  | Yes             | <isMarriedOnBoarding>| <spouseNotSsn>| <isMarriedDependent>| <markCompleteOptions>| <maritalStatus>| <hadDistributions>| <directAndsameBankAccount>| <checkMailedAndDirect>| <isRandomUploadFile>| Yes         | Yes           |

	Examples: 
	|email                               | password    | isMarriedOnBoarding | spouseNotSsn | isMarriedDependent | markCompleteOptions | maritalStatus | hadDistributions  | directAndsameBankAccount | checkMailedAndDirect | isRandomUploadFile|				
	|lf.martinez+taxchat6521@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat62381@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat47808@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat41894@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat27553@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat01341@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat99779@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat49333@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat47809@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat38052@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat97017@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat38892@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat63363@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat24112@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat11135@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat78554@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat86227@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat77725@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat24883@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat63931@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat53871@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat54914@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat09300@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat26635@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat62571@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat72717@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat05487@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat45118@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat45833@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat29948@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat98477@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat23610@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat01170@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat69493@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat48243@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat66663@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat24482@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat56325@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat4521@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat5432@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat21678@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat57932@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat97987@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat40022@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat96374@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat31241@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat21081@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat01521@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat32761@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat77239@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat4273@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat21548@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat519481@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat625497@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat03290@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat05335@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat67955@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat60816@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat17974@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat75277@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc70186@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc49650@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc04573@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc20798@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc73480@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc68374@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc99049@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc96953@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc38405@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc56563@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc81693@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc44912@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc18852@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc67148@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc18717@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc34521@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc91199@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc00341@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc48607@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc87982@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc77849@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc78673@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc74307@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc81159@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc19654@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc89089@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc98061@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc12336@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc79637@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc04971@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc55457@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc25463@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc50940@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc70423@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+sub_cc30058@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat16789@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat86066@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat25874@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat21460@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
	|lf.martinez+taxchat53579@globant.com| Abcd1234GLB | Yes                 | No           | No                 | No                  | Divorced      | No                | No                       | No                   | No				 |
