// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.1.0.0
//      SpecFlow Generator Version:3.1.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TaxChatTAFSpecFlow.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Complete participant information for massive users previously created")]
    public partial class CompleteParticipantInformationForMassiveUsersPreviouslyCreatedFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "CompleteParticipantInformationForMassiveUsers.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Complete participant information for massive users previously created", "\tIn order to complete the entire participant information\r\n\tAs a partipant user\r\n\t" +
                    "I want to upload all the required files and fill out the profile information on " +
                    "particpant page", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Complete participant information with users previously created for B2B2C users")]
        [NUnit.Framework.CategoryAttribute("completeParticipantInformationForMassiveUsers")]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat6521@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat62381@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat47808@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat41894@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat27553@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat01341@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat99779@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat49333@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat47809@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat38052@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat97017@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat38892@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat63363@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat24112@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat11135@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat78554@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat86227@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat77725@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat24883@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat63931@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat53871@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat54914@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat09300@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat26635@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat62571@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat72717@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat05487@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat45118@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat45833@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat29948@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat98477@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat23610@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat01170@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat69493@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat48243@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat66663@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat24482@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat56325@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat4521@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat5432@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat21678@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat57932@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat97987@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat40022@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat96374@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat31241@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat21081@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat01521@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat32761@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat77239@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat4273@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat21548@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat519481@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat625497@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat03290@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat05335@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat67955@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat60816@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat17974@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat75277@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc70186@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc49650@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc04573@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc20798@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc73480@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc68374@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc99049@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc96953@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc38405@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc56563@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc81693@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc44912@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc18852@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc67148@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc18717@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc34521@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc91199@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc00341@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc48607@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc87982@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc77849@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc78673@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc74307@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc81159@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc19654@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc89089@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc98061@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc12336@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc79637@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc04971@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc55457@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc25463@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc50940@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc70423@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+sub_cc30058@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat16789@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat86066@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat25874@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat21460@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        [NUnit.Framework.TestCaseAttribute("lf.martinez+taxchat53579@globant.com", "Abcd1234GLB", "Yes", "No", "No", "No", "Divorced", "No", "No", "No", "No", null)]
        public virtual void CompleteParticipantInformationWithUsersPreviouslyCreatedForB2B2CUsers(string email, string password, string isMarriedOnBoarding, string spouseNotSsn, string isMarriedDependent, string markCompleteOptions, string maritalStatus, string hadDistributions, string directAndsameBankAccount, string checkMailedAndDirect, string isRandomUploadFile, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "completeParticipantInformationForMassiveUsers"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Complete participant information with users previously created for B2B2C users", null, @__tags);
#line 7
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
 testRunner.Given(string.Format("The user have entered into participant page with a created user {0} {1}", email, password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
 testRunner.When(string.Format("He enters into upload documents option with an user created to upload all require" +
                            "d files {0}", isRandomUploadFile), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "typeDependent",
                            "firstNameDependent",
                            "lastNameDependent",
                            "dateOfBirth",
                            "ssn",
                            "dependentNotSsn",
                            "isMarriedOnBoarding",
                            "spouseNotSsn",
                            "isMarriedDependent",
                            "markCompleteOptions",
                            "maritalStatus",
                            "hadDistributions",
                            "directAndsameBankAccount",
                            "checkMailedAndDirect",
                            "isRandomUploadFile",
                            "isB2B2CUser",
                            "isCreatedUser"});
                table18.AddRow(new string[] {
                            "son",
                            "Jhon",
                            "Kent",
                            "December,7,1962",
                            "123456789",
                            "Yes",
                            string.Format("{0}", isMarriedOnBoarding),
                            string.Format("{0}", spouseNotSsn),
                            string.Format("{0}", isMarriedDependent),
                            string.Format("{0}", markCompleteOptions),
                            string.Format("{0}", maritalStatus),
                            string.Format("{0}", hadDistributions),
                            string.Format("{0}", directAndsameBankAccount),
                            string.Format("{0}", checkMailedAndDirect),
                            string.Format("{0}", isRandomUploadFile),
                            "Yes",
                            "Yes"});
#line 10
 testRunner.Then("Is validated and fill out all the information on the profile section", ((string)(null)), table18, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
